# Generated by Django 4.2.3 on 2023-07-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
