# Generated by Django 4.2.3 on 2023-07-13 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productimage_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
